### ISSUE TITLE
[WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by GiangHLe** [DanielTea/rage-analytics#2]
Hi!
I' am using your realtime_VideoStreamer.py and I meet a bug at 'create_pip' def, at line 
```
self.pipe = sp.Popen(['/home/sd092/ffmpeg-git-20180111-32bit-static/ffmpeg', "-i", self.stream_url,
                         "-loglevel", "quiet",  # no text output
                         "-an",  # disable audio
                         "-f", "image2pipe",
                         "-pix_fmt", "bgr24",
                         "-vcodec", "rawvideo", "-"],
                        stdin=sp.PIPE, stdout=sp.PIPE)
```
I think it's because the directory '/home/sd092/ffmpeg-git-20180111-32bit-static/ffmpeg' isn't exist in my pc, can you share that file on this repo.

**Comment by DanielTea** [comment]
Hi, 

sorry for the late response, this project is not under development right now. It was just a university project.

The file path is indeed just the hardcoded file path to the ffmpeg program executable. Just switch it to the file path on your computer.
